### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by kkossally** [terrencemlai/charitychoice#2]
- Your site is very professional looking with excellent styling and demonstrable attention to detail. Great work!

- [x] style your session errors

- [x] make the logout button more obvious

- [x] add demo donor and teacher login buttons

- [x] Keep doing what you're doing! 😃

**Comment by terrencemlai** [comment]
I will add the demo buttons today

**Comment by terrencemlai** [comment]
Completed.  Added button on signin form to prefill credentials for the demo account.  (I still wanted to user to click "Sign In" to replicate the process).
