### ISSUE TITLE
Splash Page

### ISSUE THREAD

**Issue by terrencemlai** [terrencemlai/charitychoice#5]
- [x] Shows prominent call-to-action buttons to generic search page for projects

- [x] Responsive for mobile

- [x] Integrates search bar

- [x] Includes suggested projects

**Comment by kkossally** [comment]
- excellent responsiveness and overall styling, it's hard to tell that this is a clone

- Is the nearby projects what you mean by suggested projects?

- [ ] replace or remove 'about us', 'help', and footer links

**Comment by terrencemlai** [comment]
Yes, I'm using "suggested projects" for now until I have an opportunity to do more localized suggestions... or recently viewed, etc.
